export const GET_ACCESSORIES = 'GET_ACCESSORIES'
export const SEARCH_ACCESSORIES = 'SEARCH_ACCESSORIES'
export const SET_DEFAULT_FILTERS = 'SET_DEFAULT_FILTERS'
export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS'
